### ISSUE TITLE
Uploading a big PNG file as an institution's logo breaks the portal

### ISSUE THREAD

**Issue by herminiogg** [EHRI/ehri-frontend#1442]
I tried to upload an image (in PNG) as an institution's log bigger than 1MB and the portal crashed. The PNG was created using a SVG file which was exported with high resolution. It would be better to validate the file and/or handling the error.

**Comment by mikesname** [comment]
Possibly related to #1198. Can I ask what the frontend error looked like? 

FYI, it should validate the image size (I think 5MB is the limit), but some weird interaction between the proxy server and the Play app was causing a crash here I never managed to solve. This could be a different issue though.

I got a load of `java.lang.OutOfMemoryError: Java heap space` errors from the thumbnail resizer at the same time, which may also be related. Could you send me the PNG to test?

**Comment by mikesname** [comment]
This is the still-unsolved proxy error, for reference:

![image](https://user-images.githubusercontent.com/871049/194293833-64d3481c-57eb-4e6f-b719-904ff1279c2f.png)

**Comment by herminiogg** [comment]
The error was a blank page. Then, I reloaded the page and I received an error message saying that the service was down (I don't really remember the wording, but it was the typical error when the portal goes down). I will send you the image by email.
