### ISSUE TITLE
XSS Injection in profile name & notes

### ISSUE THREAD

**Issue by ThomasThelen** [EHRI/ehri-frontend#1482]
Small bug where you can set your profile name to JS, which then gets executed on a page that has a note written by you.

To Reproduce:
1. Set your profile name to `<script>alert("hi")</script>`
2. Add a (non public) note somewhere
3. Refresh the page with the note
4. See the alert from step 1

**Comment by mikesname** [comment]
@ThomasThelen big thanks for finding and reporting this! I've put out a fix just now.

**Comment by ThomasThelen** [comment]
Thanks for the fix (and project)! I looked around the source to see if I could issue a PR-but I'm unfortunately not super familiar with scala. Looking through the commit now though, it looks nice. great work ^_^
