### ISSUE TITLE
Buttons for adding fields when window is shrunk do not work

### ISSUE THREAD

**Issue by herminiogg** [EHRI/ehri-frontend#1510]
When shrinking a window towards the mobile version the buttons for adding field (during the edition of a description) stop working. To solve this problem it is necessary to make the window bigger, then press the add button to get the new field created in the interface.

**Comment by mikesname** [comment]
@herminiogg any chance you could add more details and/or a screenshot? :pray:  I can't identify which particular buttons you are referring to.

**Comment by herminiogg** [comment]
Yes, you can see below a screenshot where the buttons with the plus icon are not working. I noticed now that this is only happening in the address area, those that are outside of it work normally even with a resized window.

![Screenshot 2024-07-22 122751](https://github.com/user-attachments/assets/76e63b36-b057-4feb-8d96-d6fbc6ee2910)

**Comment by mikesname** [comment]
@herminiogg  Should be fixed hopefully!

**Comment by herminiogg** [comment]
@mikesname It is indeed fixed! Thanks!
