### ISSUE TITLE
Revamping the front page...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#438]
The portal front page needs to make a decent impression. It should:
 
 - look good
 - be informative
 - be a starting point for both searching and browsing

I think we need:

 - A short introductory text recapping what EHRI is
 - A section with brief introductory text for:
  - country reports
  - archival institutions
  - documentary units

@retosp : would you have any ideas about the text? i.e: explaining EHRI in one sentence?

**Comment by valeasc** [comment]
Latest news is kind of lost in the frontpage. I suggest to improve this part visually by:
* making the separation line thicker
* adding icons (see: http://staging.teresah.php.dev.dasish.eu/ )
