### ISSUE TITLE
Fonts and typography in general...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#445]
I think we want a nicer, more distinctive and subject appropriate heading font. A standard web serif one doesn't look brilliant however.

The [Adelle](https://typekit.com/fonts/adelle-web) font (as used by the [BFI](http://bfi.org.uk) and many other places) looks very nice. Unfortunately it costs money.

**Comment by valeasc** [comment]
Minor change (but I think it makes a big, visual, difference): Can I suggest grey for the text instead of black? Particularly in the frontpage.
