### ISSUE TITLE
Improvements to sign up page/on-boarding...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#457]
- In the user feedback session one user was confused by the Google/Facebook login buttons, thinking that they would "connect" to G+/FB. Clarify that these buttons are just for login and will only ask for your email address.
- Make it clearer to users that they can add more details to their profile. After sign-up we could redirect the user to their profile page.
- Explain somewhere the benefits (if any) of signing up...

**Comment by mikesname** [comment]
Possible useful resource: http://blog.codinghorror.com/the-god-login/

**Comment by mikesname** [comment]
Part addressed in d74f10974f6b5772665e063725f72390efa05901.

**Comment by valeasc** [comment]
I signed up and everything worked fine. Minor thing: the confirmation email message could be improved. I got a message with the EHRI logo missing and the letters from the top message are jammed together 
![ehri_subscription_message](https://cloud.githubusercontent.com/assets/6930601/5840055/b4fb3e4a-a18a-11e4-9fdd-0f92ed9ce3b0.JPG)
