### ISSUE TITLE
Footer menu?

### ISSUE THREAD

**Issue by retosp** [EHRI/ehri-frontend#475]
Are we planning to have a footer on the portal. I guess there's still some information that we'll have to provide somehow:
- About us: links to a page with some basic info about the portal. The about us page can then link to the project website for more in-depth information
- Terms of use/privacy stuff: links to a page with the legal guff Dirk is currently writing.
- Contact us: I guess given that the NIOD is in charge we should give their address somewhere including a suitable contact email address.
- Anythng else?

Also, I guess we'll have to display the EC logo somewhere in the footer given that they paid for it.

**Comment by valeasc** [comment]
Personally, I think ABOUT should also be in the header. It's easier to find for the first-time-visitor who wants to know what EHRI is all about.

**Comment by valeasc** [comment]
I would also move the language options to the header. If it becomes too messy to have all the languages listed in the header, then perhaps a solution could be to have a *Choose a language* menu (see Europeana: http://www.europeana.eu/ )

**Comment by mikesname** [comment]
:+1:

**Comment by mikesname** [comment]
The issue with the languages in the header menu is that it's difficult to see how to switch to or from your language if it's available. Listing all the languages at the top takes too much space, so moving them back to the bottom might be the best option.

**Comment by retosp** [comment]
I’m happy to move it back into the footer.

**Comment by mikesname** [comment]
Going to call this fixed in 177a76f6509f26026fd21a178695f8941d3956db.
