### ISSUE TITLE
Guides: breadcrumb view of hierarchy doesn't work

### ISSUE THREAD

**Issue by michalfrankl** [EHRI/ehri-frontend#517]
As in the portal interface, the superordinated hierarchy for an item should be displayed as a breadcrumb and not as a numbered list:

http://portal.aehri.dans.knaw.nl/guides/terezin/browse?kw%5B%5D=terezin-victims-person-iti-1296855&kw%5B%5D=&kw%5B%5D=&kw%5B%5D=

Moreover, for some collections titles (specifically for the JMP Terezín collection) the identifier is displayed instead of the title.

The issue with the title is the case for item's detail page too:

http://portal.aehri.dans.knaw.nl/guides/terezin/document/cz-002279-collection-jmp-shoah-t-collection-jmp-shoah-t-2-collection-jmp-shoah-t-2-a-collection-jmp-shoah-t-2-a-2-collection-jmp-shoah-t-2-a-2s-collection-jmp-shoah-t-2-a-2s-146-collection-jmp-shoah-t-2-a-2s-146-001-document-jmp-shoah-t-2-a-2s-146-001-213

**Comment by mikesname** [comment]
I believe this was fixed at some point with the changes to tree depth serialization.
