### ISSUE TITLE
Guides: map - not all locations displayed

### ISSUE THREAD

**Issue by michalfrankl** [EHRI/ehri-frontend#523]
The map in the Terezín guide (https://portal.ehri-project.eu/guides/terezin/geography) includes only a smaller part of the available locations so that the view is inconsistant. When zooming in and out and while moving the map a little, more and more locations appear. Thibault was of the opinion that displaying all places is too heavy but the result is highly problematic since we provide only partial data and hardly can explain to users to play with the map as long as other locations don't pop up :)

**Comment by mikesname** [comment]
I've changed a few things here, please have a look [on staging](http://portal.aehri.dans.knaw.nl/guides/terezin/geography) and see if it's better or worse than before.

**Comment by michalfrankl** [comment]
Thanks, this is much better. Is there a way to show the map zoomed out approx. two steps, so that most of the Terezín fortress is visible? I know that's a lot of locations, but it seems to work flawlessly when zooming out now.

I tried to centre the map on the Terezín main square (it's clearly visible on the map) and changed the coordinates accordingly, but the map still loads centred elsewhere.

**Comment by mikesname** [comment]
Okay done (I expect that can be made configurable somehow, will have a look.)

**Comment by michalfrankl** [comment]
Thanks - it looks good, but it's not centred on the selected coordinates. Is that hard coded somewhere?

**Comment by michalfrankl** [comment]
We have had a discussion about the layout of the second guide, including the layout of the Geographic guide. At the moment, we provide information about three Jewish communities/towns: Vienna, Budapest, Prague. We came to the conclusion that it would be very useful to be able to start at a page with a map of all three locations and to be able to follow links above the map which would zoom into the individual towns. Is that possible, via link parameters or some easy JS, withough much hassle?
