### ISSUE TITLE
YV descriptions - result list - inconsistent language of description in title and content preview

### ISSUE THREAD

**Issue by ygherman** [EHRI/ehri-frontend#547]
when looking at the item list under the [repository](http://portal.aehri.dans.knaw.nl/admin/institutions/il-002798), the language of the title is English and the content preview is in Hebrew

see screen shot:
![result list](https://cloud.githubusercontent.com/assets/2689048/6449335/c1643bb0-c128-11e4-997d-8b1c070e6ab3.PNG)

Could that be change that the default will be English and that the language of the title and of the content preview will be consistent?

**Comment by ygherman** [comment]
now this problems occurs in the production environment.
look down at the list of descriptions under YV repository:
https://portal.ehri-project.eu/institutions/il-002798

![image](https://cloud.githubusercontent.com/assets/2689048/6705538/75f2cd9e-cd5e-11e4-8803-dc15b84f4d24.png)

**Comment by mikesname** [comment]
I know what this is, will have a look.

**Comment by mikesname** [comment]
@ygherman could you check out the build on staging and see if it does what you want? I've played around with text direction as well, but it's experimental...

http://portal.aehri.dans.knaw.nl/units?lang=heb&lang=lit&page=3

**Comment by mikesname** [comment]
@ygherman assuming you're happy with this.

**Comment by ygherman** [comment]
The result list is consistent in terms of language, but would it be possible to change the default language of the content preview to English?
