### ISSUE TITLE
To-dos before submission of final portal deliverable

### ISSUE THREAD

**Issue by retosp** [EHRI/ehri-frontend#567]
We have to submit the final portal deliverable in the first couple of weeks of April. Before we can do that we have to:

- Publish the frontend source code in the EHRI organisation on Github
- Add licence information to the source code. From the last PMB minutes: "Mike recommends to use European Union Public Licence v1.1 with listing all coding partners in the copyright notice."

Some more detailed info from Mike P about the licence here:

"
Hi Anne,

Well, not a detailed proposal, but just a recommendation to use European Union Public Licence 
v1.1 with listing all coding partners in the copyright notice.

so it would look something like this:

/* 
 * Copyright 2015 Data Archiving and Networked Services (an institute of 
Koninklijke Nederlandse Akademie Van Wetenschappen), King's College 
London, Georg-August-Universitaet Goettingen Stiftung Oeffentlichen Rechts 
 * 
 * Licensed under the EUPL, Version 1.1 or – as soon they will be approved by 
 * the European Commission - subsequent versions of the EUPL (the "Licence"); 
 * You may not use this work except in compliance with the Licence. 
 * You may obtain a copy of the Licence at: 
 * 
 * https://joinup.ec.europa.eu/software/page/eupl 
 * 
 * Unless required by applicable law or agreed to in writing, software  
 * distributed under the Licence is distributed on an "AS IS" basis, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either 
express or implied. 
 * See the Licence for the specific language governing 
 * permissions and limitations under the Licence. 
 */

The reasoning for using EUPL is 
"Because of the European and multilingual nature of the EHRI project, and our code sharing 
philosophy, we should use the European Union Public Licence v1.1. This is compatible with 
GPL v2, but available in 22 languages (users can choose) and matches with legal terms in all 
jurisdictions."

Info is here:
Licence introductions + texts: https://joinup.ec.europa.eu/software/page/eupl/licence-eupl 
How to use: https://joinup.ec.europa.eu/software/page/eupl/eupl-guidelines

BTW we have also used this licensing on DASISH.

Regards,
Mike
"

**Comment by mikesname** [comment]
These are both done.
