### ISSUE TITLE
Make email addresses of users that use the feedback form visible

### ISSUE THREAD

**Issue by retosp** [EHRI/ehri-frontend#584]
When users use the feedback form on the portal their email-addresses are not visible in the emails that are forwarded to feedback@ehri-project.eu. This makes it impossible/difficult for us to reply to their feedback. This applies to both logged-in users and users that fill-in the optional email-address field on the form.

Could this be changed?

**Comment by mikesname** [comment]
OK noted. FYI, their email should be in the "reply-to" header, e.g. you can just reply to them. However I'll add this to the email somewhere.
