### ISSUE TITLE
Funding information in footer

### ISSUE THREAD

**Issue by retosp** [EHRI/ehri-frontend#608]
Apparently there is a standard phrase that needs to be included in all outputs from EHRI, so I'm afraid we need to change our neat exiting footer text "The EHRI Project is supported by the European Commission" with something much more cluncky, namely:

"The EHRI project has received funding from the European Union’s Seventh Framework Programme under grant agreement No 261873, and from the European Union’s Horizon 2020 research and innovation programme under grant agreement No 654164"

Can we accommodate this in the footer (by using small font, etc.) or do we have to hide it elsewhere?

**Comment by mikesname** [comment]
Who can we ask for the translations? I'll do the English now and we can fix those later.

**Comment by retosp** [comment]
A good question – I think there might be a few more changes to texts in the coming weeks. So we probably have to send another batch of texts of to the translators in due course – i.e. once we have a reasonable amount of text (hardly worth to do it for every couple of sentences that we change). Can we easily extract all the strings that have been changed since we last translated, or do we have to manually keep a record somewhere of all the strings we have altered?

**Comment by mikesname** [comment]
Mmmn, might look better in the "about" page since it is a bit cluttered.

![image](https://cloud.githubusercontent.com/assets/871049/7839698/b798d7b6-048b-11e5-8f4b-117bdc054420.png)

I think I can figure it out the string changes via the source control.

**Comment by retosp** [comment]
Putting it into the “about page” is ok with me. We can leave the generic “EHRI is supported by the European Union” in the footer, and have the more detailed info in the about page.

**Comment by mikesname** [comment]
This sentence more or less exists currently on the about page, but I've moved it from para 3 to the end:

> The EHRI portal is one of the main outcomes of the European Holocaust Research Infrastructure (EHRI) project, a consortium bringing together Holocaust researchers, archivists and digital humanists from more than 20 institutions. The EHRI portal is an expanding resource and new information and features are continuously added.

> EHRI is both a digital infrastructure and a human network. In addition to creating the portal, the EHRI project has also developed a free-to-use Online Course on Holocaust Studies, and hosts a varied programme of activities and events including a Fellowship programme, Summer Schools, expert workshops and conferences. More information on the project's background, contributing institutions and activities is available on the project website.

> The EHRI project has received funding from the European Union's Seventh Framework Programme under grant agreement No 261873, and from the European Union's Horizon 2020 research and innovation programme under grant agreement No 654164.

**Comment by retosp** [comment]
Great – thank you. Are you keeping track of English texts we change for the purpose of translation or can we identified such texts automatically?

**Comment by mikesname** [comment]
I've tagged the build corresponding to the last batch of translations and it's quite straightforward to diff against it to see any changes which will need to be translated.

**Comment by retosp** [comment]
Great, Mike ☺
