### ISSUE TITLE
Addition to Terms & Condition

### ISSUE THREAD

**Issue by retosp** [EHRI/ehri-frontend#611]
There's another little addition we have to make to our T&C at https://portal.ehri-project.eu/terms.

Could we add the following sentence right at the end of the copyright statement:

"All the content of this website only reflects the views of the author(s)and/or EHRI, and the European Commission cannot be held responsible for any use that may be made of the information it contains."

This is to ensure that we comply the EC's legal requirements ...

**Comment by retosp** [comment]
Hi Mike,

Could we already publish this addition in English on the portal even before we have it translated, please?

Cheers,
Reto

**Comment by mikesname** [comment]
Done.
