### ISSUE TITLE
is deleted item still visible?

### ISSUE THREAD

**Issue by vddaelen** [EHRI/ehri-frontend#658]
https://portal.ehri-project.eu/admin/units/cz-002261-436
shows there is one item, but it does not show a description.
the history shows it has been deleted, so why is it still visible?
https://portal.ehri-project.eu/admin/units/cz-002261-436/history

**Comment by mikesname** [comment]
The (only) description has been deleted, but not the item itself. In the formal logic of the system, _it exists, but we do not know anything about it_. You can delete the item itself if you wish.

Note: in the change log it says "Description deleted". If you delete the item, it'll say something like "Item deleted".
