### ISSUE TITLE
Test in IE9+

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#69]
People are, sadly, using it :(

**Comment by mikesname** [comment]
Re-opening since we have new breakage.

**Comment by PonteIneptique** [comment]
I assume you don't mind if I assign you ;)

**Comment by mikesname** [comment]
NO YOU MUST DO THIS WORK! :facepunch:

**Comment by PonteIneptique** [comment]
![Issue and notification](http://m.memegen.com/zz5wqj.jpg)

**Comment by mikesname** [comment]
![i3dgx](https://cloud.githubusercontent.com/assets/871049/6369599/daca4812-bcdf-11e4-91e4-420489dd74c7.jpg)

[LINK](https://help.github.com/articles/removing-yourself-from-a-collaborator-s-repository/)

**Comment by PonteIneptique** [comment]
![I want to stay](http://m.memegen.com/em3z3k.jpg)
