### ISSUE TITLE
Private-by-default notes confuses people...

### ISSUE THREAD

**Issue by mikesname** [EHRI/ehri-frontend#957]
People leaving notes on descriptions don't seem to realise that their notes are private-by-default. We should probably make this more obvious.

**Comment by ixt** [comment]
I'd suggest adding "Private note" Affixed before the - next to the name. Leaving this off for public notes.

**Comment by mikesname** [comment]
Changed notes to public by default in 468b530b63b1c9411207523895800e855915e938
